---
title: "README"
author: "Clay McKean"
date: "2024-11-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Gulf of Alaska Bottomfish

This project assesses the halibut, rockfish, and lingcod sport fisheries in Southcentral Alaska by collecting biological
samples and conducting angler interviews out of the ports of Homer, Seward, Whittier, Valdez, and Kodiak.  
The operational plan for this project can be found here: <https://www.adfg.alaska.gov/FedAidPDFs/ROP.SF.2A.2022.24.pdf>


## Project Objectives

### Primary Objectives
1) Estimate the mean weight of Pacific halibut taken by each user in each area of Southcentral
Alaska (Kodiak, Lower Cook Inlet, Central Cook Inlet, North Gulf Coast, Eastern Prince
William Sound, and Western Prince William Sound), such that the mean weight estimates
for each user group in each area are within 0.20 of the true mean weight at least 90% of the
time.\
2) Estimate the length composition of the Pacific halibut harvest by area such that the
estimated proportions are within 0.20 of the true proportions at least 95% of the time.\
3) Estimate the species composition by port of the rockfish harvest landed at Kodiak, Homer,
Seward, Whittier, and Valdez during May through September such that the estimated
proportions of each species are within 0.20 of the true proportions at least 95% of the time.\
4) Estimate the age, length, and sex composition by port of the principal rockfishes landed at
Kodiak, Homer, Seward, Whittier, and Valdez during May through September such that
the estimated proportions are within 0.20 of the true proportions at least 95% of the time.\
5) Estimate the age, length, and sex composition by port of the lingcod harvest landed at
Kodiak, Homer, Seward, Whittier, and Valdez during July through September such that
the estimated proportions are within 0.20 of the true proportions at least 90% of the time.

### Secondary Objectives
1) Identify differences in the geographic distribution of groundfish effort and harvest between
user groups and across years for each port during May through September.\
2) Estimate the proportion of the Pacific halibut harvest that was cleaned (and carcasses
discarded) at sea at each port. These estimates will be used to stratify length and weight
estimates at ports where cleaning at sea is prevalent.\
3) Estimate the proportions of released Pacific halibut that were caught on circle hooks versus
other types of hooks at each port. This information is needed to refine estimates of halibut
release mortality in the sport fishery.\
4) To refine discard mortality estimates, gather data on the depths of capture for pelagic and
nonpelagic rockfish that were released.\
5) Estimate the proportions of released lingcod that were of sublegal (under 35 inches total
length) and legal size (35 inches and greater) for ports with a minimum size limit
regulation. These data will provide information on future recruitment and abundance
indices used for future stock assessments.\
6) Biological data will be collected from salmon sharks (Lamna ditropis), Pacific sleeper
sharks (Somniosus pacificus), and spiny dogfish (Squalus acanthias) harvested in the sport
fishery in order to estimate the age, length, sex composition, and spatial distribution of the
harvest. No sampling objectives are established for sharks because harvests are too small
to generate reliable estimates for any given year. It is expected that age, length, and sex
data will be compiled across a number of years and combined with commercial harvest
sampling and other research programs to estimate life history parameters.
